

services:

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nodejs:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: node:20-alpine
    restart: unless-stopped
    env_file:
      - src/.env.development
    extra_hosts:
      - "host.docker.internal:host-gateway"
